// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelFull.Server.Migrations
{
    [DbContext(typeof(HotelContext))]
    partial class HotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HotelAPI.Models.Advertisement", b =>
                {
                    b.Property<int>("AdvertisementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdvertisementID"));

                    b.Property<int?>("Adpriority")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("URL")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("AdvertisementID")
                        .HasName("PK__Advertis__C4C7F42D6CB86221");

                    b.HasIndex("ImageID");

                    b.ToTable("Advertisement");
                });

            modelBuilder.Entity("HotelAPI.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<TimeOnly?>("BreakTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("ClockInStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IDNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EmployeeID")
                        .HasName("PK__Employee__7AD04FF13A491557");

                    b.HasIndex("ImageID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("HotelAPI.Models.HotelInfo", b =>
                {
                    b.Property<int>("HotelInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HotelInfoID"));

                    b.Property<string>("CheckInTime")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("05:00");

                    b.Property<string>("CheckOutTime")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("17:00");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("teste@exemplo.us");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("Rua Inexistente, 2000");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("健行小飯店");

                    b.Property<decimal>("Latitude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8, 6)")
                        .HasDefaultValue(-48.817993m);

                    b.Property<decimal>("Longitude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(9, 6)")
                        .HasDefaultValue(-15.930247m);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("3121286800");

                    b.HasKey("HotelInfoID")
                        .HasName("PK__HotelInf__54385C7A560238A4");

                    b.ToTable("HotelInfo");
                });

            modelBuilder.Entity("HotelAPI.Models.Image", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<byte[]>("ImageBinary")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int?>("ImageTypeID")
                        .HasColumnType("int");

                    b.HasKey("ImageID")
                        .HasName("PK__Image__7516F4ECA7933EFB");

                    b.HasIndex("ImageTypeID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("HotelAPI.Models.ImageType", b =>
                {
                    b.Property<int>("ImageTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImageTypeID"));

                    b.Property<string>("ImageTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ImageType");

                    b.HasKey("ImageTypeID")
                        .HasName("PK__ImageTyp__B9E9EB969A0417B4");

                    b.ToTable("ImageType");
                });

            modelBuilder.Entity("HotelAPI.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("MemberID")
                        .HasName("PK__Member__0CF04B38D0B45132");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("HotelAPI.Models.News", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("publishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("visable")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("HotelAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ProductTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ProductID")
                        .HasName("PK__Product__B40CC6ED4D04B220");

                    b.HasIndex("ImageID");

                    b.HasIndex("ProductTypeID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("HotelAPI.Models.ProductType", b =>
                {
                    b.Property<int>("ProductTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductTypeID"));

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ProductTypeName");

                    b.HasKey("ProductTypeID")
                        .HasName("PK__ProductT__A1312F4E04AC0399");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("HotelAPI.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastCleaned")
                        .HasColumnType("datetime");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("RoomTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("RoomID")
                        .HasName("PK__Room__32863919D72E2158");

                    b.HasIndex("ImageID");

                    b.HasIndex("RoomTypeID");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("HotelAPI.Models.RoomBooking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<string>("BackOfficeFeedback")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<string>("FrontDeskNotes")
                        .HasColumnType("longtext");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("BookingID")
                        .HasName("PK__RoomBook__73951ACD10204ED1");

                    b.HasIndex("MemberID");

                    b.HasIndex("RoomID");

                    b.ToTable("RoomBooking");
                });

            modelBuilder.Entity("HotelAPI.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoomTypeID"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoomTypeID")
                        .HasName("PK__RoomType__BCC89611463B39DC");

                    b.HasIndex("ImageID");

                    b.ToTable("RoomType");
                });

            modelBuilder.Entity("HotelFull.Server.Models.ProductOrderItem", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("ProductOrderOrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ProductOrderOrderID");

                    b.ToTable("ProductOrderItem");
                });

            modelBuilder.Entity("ProductOrder", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<string>("BackOfficeFeedback")
                        .HasColumnType("longtext");

                    b.Property<string>("FrontDeskNotes")
                        .HasColumnType("longtext");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PaymentStat")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("OrderID")
                        .HasName("PK__ProductO__C3905BAF0951D809");

                    b.HasIndex("MemberID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductOrder");
                });

            modelBuilder.Entity("HotelAPI.Models.Advertisement", b =>
                {
                    b.HasOne("HotelAPI.Models.Image", null)
                        .WithMany("Advertisement")
                        .HasForeignKey("ImageID");
                });

            modelBuilder.Entity("HotelAPI.Models.Employee", b =>
                {
                    b.HasOne("HotelAPI.Models.Image", "Image")
                        .WithMany("Employee")
                        .HasForeignKey("ImageID")
                        .HasConstraintName("FK__Employee__ImageI__52593CB8");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("HotelAPI.Models.Image", b =>
                {
                    b.HasOne("HotelAPI.Models.ImageType", "ImageType")
                        .WithMany("Image")
                        .HasForeignKey("ImageTypeID")
                        .HasConstraintName("FK__Image__ImageType__5070F446");

                    b.Navigation("ImageType");
                });

            modelBuilder.Entity("HotelAPI.Models.Product", b =>
                {
                    b.HasOne("HotelAPI.Models.Image", "Image")
                        .WithMany("Product")
                        .HasForeignKey("ImageID")
                        .HasConstraintName("FK__Product__ImageID__59063A47");

                    b.HasOne("HotelAPI.Models.ProductType", "ProductType")
                        .WithMany("Product")
                        .HasForeignKey("ProductTypeID")
                        .HasConstraintName("FK__Product__Product__5812160E");

                    b.Navigation("Image");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("HotelAPI.Models.Room", b =>
                {
                    b.HasOne("HotelAPI.Models.Image", "Image")
                        .WithMany("Room")
                        .HasForeignKey("ImageID")
                        .HasConstraintName("FK__Room__ImageID__5441852A");

                    b.HasOne("HotelAPI.Models.RoomType", "RoomType")
                        .WithMany("Room")
                        .HasForeignKey("RoomTypeID")
                        .IsRequired()
                        .HasConstraintName("FK__Room__RoomTypeID__534D60F1");

                    b.Navigation("Image");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelAPI.Models.RoomBooking", b =>
                {
                    b.HasOne("HotelAPI.Models.Member", "Member")
                        .WithMany("RoomBooking")
                        .HasForeignKey("MemberID")
                        .IsRequired()
                        .HasConstraintName("FK__RoomBooki__Membe__5629CD9C");

                    b.HasOne("HotelAPI.Models.Room", "Room")
                        .WithMany("RoomBooking")
                        .HasForeignKey("RoomID")
                        .IsRequired()
                        .HasConstraintName("FK__RoomBooki__RoomI__571DF1D5");

                    b.Navigation("Member");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelAPI.Models.RoomType", b =>
                {
                    b.HasOne("HotelAPI.Models.Image", "Image")
                        .WithMany("RoomType")
                        .HasForeignKey("ImageID")
                        .HasConstraintName("FK__RoomType__ImageI__5535A963");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("HotelFull.Server.Models.ProductOrderItem", b =>
                {
                    b.HasOne("HotelAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductOrder", "ProductOrder")
                        .WithMany("ProductOrderItem")
                        .HasForeignKey("ProductOrderOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductOrder");
                });

            modelBuilder.Entity("ProductOrder", b =>
                {
                    b.HasOne("HotelAPI.Models.Member", "Member")
                        .WithMany("ProductOrder")
                        .HasForeignKey("MemberID")
                        .IsRequired()
                        .HasConstraintName("FK__ProductOr__Membe__59FA5E80");

                    b.HasOne("HotelAPI.Models.Product", null)
                        .WithMany("ProductOrder")
                        .HasForeignKey("ProductID");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("HotelAPI.Models.Image", b =>
                {
                    b.Navigation("Advertisement");

                    b.Navigation("Employee");

                    b.Navigation("Product");

                    b.Navigation("Room");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelAPI.Models.ImageType", b =>
                {
                    b.Navigation("Image");
                });

            modelBuilder.Entity("HotelAPI.Models.Member", b =>
                {
                    b.Navigation("ProductOrder");

                    b.Navigation("RoomBooking");
                });

            modelBuilder.Entity("HotelAPI.Models.Product", b =>
                {
                    b.Navigation("ProductOrder");
                });

            modelBuilder.Entity("HotelAPI.Models.ProductType", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("HotelAPI.Models.Room", b =>
                {
                    b.Navigation("RoomBooking");
                });

            modelBuilder.Entity("HotelAPI.Models.RoomType", b =>
                {
                    b.Navigation("Room");
                });

            modelBuilder.Entity("ProductOrder", b =>
                {
                    b.Navigation("ProductOrderItem");
                });
#pragma warning restore 612, 618
        }
    }
}
